version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - db:/data/db

  node:
    depends_on:
      - mongo
    build:
      context: .
      target: development
      args:
        - SKIP_TESTS=true
    image: weather-api:development
    environment:
      - NODE_ENV=development
      - DEBUG=weather-api:*
      - MONGO_DB_URI=mongodb://mongo:27017/weather-api
      - PORT=4000
      - OPEN_WEATHER_API_KEY=<your-open-weather-map-api>
    ports:
      - '4000:4000'
volumes:
  db:
